version: "3.9"
   
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:80
    command: ["nginx", "-g", "daemon off;"]
  back:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_USER=covid
      - DB_NAME=covid
      - DB_PASS=40Njd;c,
      - DB_HOST=192.168.56.1