# Generated by Django 4.0.2 on 2022-02-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_value', models.DateField()),
                ('country_code', models.CharField(max_length=4)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('stringency_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stringency', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
