# Generated by Django 4.0.2 on 2022-02-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='covid_data',
            unique_together={('date_value', 'country_code')},
        ),
    ]
